# Generated by Django 5.1.2 on 2024-11-02 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0003_alter_blog_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
