# Generated by Django 5.1.2 on 2024-11-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0007_rename_coment_comment_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(max_length=250),
        ),
    ]
